[package]
name = "deluge"
version = "0.1.0"
edition = "2021"

[dependencies]
pin-project = "1.0"
futures = "0.3"
num_cpus = "1.13"

#[dev-dependencies]
more-asserts = "0.3"
tokio = { version = "1.20", features = ["full"] }